### ISSUE TITLE
Waves are not "waves"

### ISSUE THREAD

**Issue by SweatForMyLife** [Tropicraft/Tropicraft#113]
My waves dont work?
My Version: 1.6.4
My added mods: Optifine, AnimatedPlayerMod, Backpacks mod
Screenshot:
![2016-06-18_16 29 19](https://cloud.githubusercontent.com/assets/20014679/16171552/e2e0383e-3571-11e6-8465-7e3194c87450.png)

The water is blinking

Thanks for reading

**Comment by CitiesXL2815** [comment]
you got to turn on the waves in the tornado mod config and 1.6.4 is outdated version, tropicraft has moved onto 1.7.10 and now updating the mod to 1.9.4, any change may not be fixed in 1.6.4

**Comment by SweatForMyLife** [comment]
I will try to turn the waves on. The problem on the version 1.7.10 is that there is no Weather Mod...When I install the 1.7.10 and open the Zip-File there is only TCSchematics and Tropicraft...then I open the Tropicraft folder and it doesnt show the weather mod (with the leaves falling down from trees)..so I don't know why you put those mods out in the 1.7.10 version? If I install this Weather Mod manually...will this work in the Tropicraft dimension?
Sorry for my bad english!
Thanks for the reply :)

**Comment by CitiesXL2815** [comment]
corosus weather mod outdated it means there not going to be weather mod for 1.7.10, but theres one localized weather mod and it doesn't have waves because of the issue corosus is having problems with so install that if that helps, it still gives you wind and storms, but not the waves, now the big questions should be left up to Corosus and Cojo for more information, so you should ask them for more help, i'm sure they may help you figure out the problem, message them on IRC, twitter or here in github.

**Comment by SweatForMyLife** [comment]
But there isnt any wind in 1.7.10? Thanks for the replay anway :)

**Comment by Cojomax99** [comment]
Nope, I think wind wasn't updated to 1.7.10. And I don't think waves were in that version, either.

**Comment by Cojomax99** [comment]
Closing as there are no longer waves in the mod...for now ;)
