### ISSUE TITLE
Cannot pump tropics water with BC pump + tropics water has no texture in railcraft tank.

### ISSUE THREAD

**Issue by MFernflower** [Tropicraft/Tropicraft#16]
That's all folks.

**Comment by Cojomax99** [comment]
Will need someone to confirm this is still an issue in the upcoming release.

**Comment by Adaptivity** [comment]
BC pump now works but tropics water still has no texture in any reservoirs.

**Comment by Adaptivity** [comment]
Righ-click now works, it doesn't crash and tropics water has texture but pump no longer works. Possibly due to fluid changes in Forge 1155+, so pump can recognize the fluid but can't pump it in any reservoir. What about updating to new Forge? Also, OpenBlocks reservoir name (which is displayed by waila) goes insane when it has tropics water. Can't describe it, you should check it yourself :smile:

**Comment by NotActuallyTerry** [comment]
Issue no longer relevant due to 1.10.2 update & related code blending/rebashing/whatever those blurry few months were
