### ISSUE TITLE
Leaves Don’t Decay 

### ISSUE THREAD

**Issue by GoldenGod48** [Tropicraft/Tropicraft#224]
No tree added by this mod has leaves that decay. They are like solid, regular blocks. Even if I break all of them, except for the fruit trees, I don’t get any saplings either.

**Comment by Cojomax99** [comment]
Leaf decay on our trees are very tricky because of their size / structure. Leaf decay is normally based on adjacent leaves, but with palm trees and big trees that isn't the case for us. We decided it's better to have no leaf decay than leaf decay that pushes into other trees or does not function properly. Sorry :(
