### ISSUE TITLE
The umbrellas is not colorful

### ISSUE THREAD

**Issue by BalintXHD** [Tropicraft/Tropicraft#229]
The unbrellas is not colorful, please fix it.

**Comment by Cojomax99** [comment]
Which version? Try relaunching your game and seeing if it is still an issue.

**Comment by SirBlockles** [comment]
Can confirm this is still an issue (at least as of 1.12.2, ver. 7.1.3.61) - any colored placeable entities (umbrellas, rafts, lawn chairs) spawn as a black one, rather than the intended color.

**Comment by kencinder** [comment]
Java and Forge version etc is probably helpful when reporting issues., I do not experience the issue with colors for umbrellas, chairs or beach floats on my server running Tropicraft 7.1.3.61 or 7.1.3.62.

Java Version - OpenJDK 64-Bit Server VM, version 1.8.0_162
Forge - 1.12.2 -14.23.2.2611
SpongeForge - 1.12.2-2611-7.1.0-BETA-3000

It should be a requirement to list these things when posting issues, as I have myself found issues that have been related to a specific entry in the above list. eg - [this](https://github.com/SpongePowered/SpongeForge/commit/c45b1b179c58e3c78e761e27a567a64397a65237) that was causing the Tropicraft world to not save on my server, which I reported and tested the fix for.
