### ISSUE TITLE
Issues with the 1.12.2 version as of 27.02.2018

### ISSUE THREAD

**Issue by CyprinusCarpio** [Tropicraft/Tropicraft#235]
I thought i will share my opinion on the build i got my hands on to make the overall experience better.

- I did not find any Ashen trees. Bad luck perhaps.
- I did not find any Easter Island heads, those with precious material eyes.
- Bodies of water should be much shallower in my opinion.
- I think more patches of grass should generate, because its lack sometimes is very apparent.
- Magic mushrooms generate just like flowers, i dont remember them doing so in earlier versions.
- Most of tree leaves generate in bowl-like manner, leaving a part of tree trunk logs exposed from the top.

**Comment by Cojomax99** [comment]
- You've had bad luck - there are quite a few Kapok (Ashen "Home") Trees
- That is a bug that has since been fixed
- We intentionally made water higher for more scuba diveability
- I have added a bit more tall grass now
- Magic mushrooms are awesome and have always generated, though normally just around rainforest biomes. Good eye, I'll think about how to handle this
- This has always been the design of these trees. Just the way they are! ¯\_(ツ)_/¯
