### ISSUE TITLE
I cannot craft anything with bamboo!

### ISSUE THREAD

**Issue by Sunconure11** [Tropicraft/Tropicraft#243]
It appears I cannot use bamboo shoots in recipes at all, for recipes relating to this mod. Or at least, JEI is showing that.

Edit: It appears you forgot to rename the bamboo shoot item in a lot of things.

**Comment by Immaculala** [comment]
This issue is marked as Fixed, but I have the same problem (tropicraft-MC1.12.2-7.1.1.56) which is the most recent version uploaded.
As a result, I tried an earlier version of Trop (tropicraft-MC1.10.2-7.0.3.145) but had problems with that too (logged as an issue).
I'm desperate to play this mod .............

**Comment by tterrag1098** [comment]
It's not fixed until these changes are merged.

**Comment by Immaculala** [comment]
Ahhh ..... sorry. I'm not familiar with how these things work.
I saw a spotlight on this mod and have been dying to play it - looks fantastic :)
