### ISSUE TITLE
More Bamboo variants

### ISSUE THREAD

**Issue by NotActuallyTerry** [Tropicraft/Tropicraft#460]
[LT Discord](https://canary.discord.com/channels/444746940761243652/992797246234038332/995337041141309442)

Logic mentioned we should have Bamboo variants for wooden blocks (e.g. Stairs, Slabs, Walls)

**Comment by ChaseCarlson** [comment]
Perhaps he meant more bamboo variants of regular Minecraft items? Bamboo tools, bamboo boats, bamboo pressure plates, bamboo buttons, bamboo signs, etc. They would all just be retextures of vanilla items with bamboo in the name. Interesting idea, though you should ask Logic since you said you didn't get a chance to ask him what he really meant by this.

What are your thoughts?

**Comment by NotActuallyTerry** [comment]
Updated with what Logic said.

Having Bamboo tools & Bamboo variants of blocks could be good, though it might come down to balancing tool tiers as wood is widely available.

**Comment by Cojomax99** [comment]
We have decided against implementing this feature request.
